### ISSUE TITLE
element 想实例化 以后 再生成

### ISSUE THREAD

**Issue by mudenglong** [aralejs/events#15]
我根据需要new 5个Line 组件（同样使用 aralejs-widget），我本来打算在Line 组件里面，setup里面生成 画line的html，但是需要在new的时候就要输入element的名字，否则不能使用event 的方法，

能不能  动态指定 element?

**Comment by popomore** [comment]
Widget 生命周期生成 element 在 setup 之前，你可以传一个 template—

**Comment by mudenglong** [comment]
之前已经查到，谢谢哈
