### ISSUE TITLE
注册事件时可否支持defer回调

### ISSUE THREAD

**Issue by huipengyu** [aralejs/events#2]
考虑下面的情景：
- 一段向后端保存数据代码，监听到某个event后再执行， 但希望在callback list的最后执行。
- 一些render功能代码，也会希望在监听某个event时，被最后执行

这样defer一下这个callback的apply，就可以简单实现了。

当然，注册事件的时候可以直接挂载一个带有defer特性的函数， 但是觉得如果能配置会更方便一些。
例如on的时候传个参数{defer:true}.

---

注：如果传个config形式的参数，就可以附加更多的特性了，例如:

``` javascript
{
    defer : true,   //推迟执行
    once : true,   //只执行一次
    onerror : DEFAULT_ERROR_HANDLE,
    blah blah....
}
```

这样符合arale的理念吗？

**Comment by lifesinger** [comment]
目前 Arale 的 events 是一个非常朴素的事件触发、监听、卸载机制，不涉及任何复杂的逻辑。

对于事件来说，理想情况下，当一个事件触发时，是向外面无差别抛出消息的，所有监听该事件的处理器，理论上应该彼此无顺序关系的接收到该消息，这就如广播电台发射信号一样，所有收音机收到消息的时机，跟其他收音机没关系，只跟当前收音机的地理位置等因素有关。

因此对于监听器来说，不存在谁是第一个，也不存在谁是最后一个。

之所以存在顺序，是因为 JavaScript 的单线程机制导致，理论上事件机制应该是多线程抛射式的，彼此无直接影响。

defer 特性，包括 once 等，都属于 user land 的逻辑，建议有类似需求时，在使用层面去解决，而不是让类库去支持。

类似的理念，可以参考 Backbone 的 events，也是保持简单，保持极简，更多的考虑什么特性可以去掉，而不是增加。

**Comment by huipengyu** [comment]
OK，理解，赞同
站在 Arale 的角度，保持极简会带来更好的普适性。我们应用的特点会更个性一些，原来我们就是改自Backbone的Events。
我们会考虑在Arale的Events上做一些aspect方式的修改，来满足自己个性的需求，同时也能完整保留Arale的events。
