### ISSUE TITLE
代码应该有兼容问题 IE8- 直接报错吧

### ISSUE THREAD

**Issue by guojunsky** [aralejs/events#22]
if (isFunction(receiver)) {
    for (var key in proto) {
      if (proto.hasOwnProperty(key)) {
        receiver.prototype[key] = proto[key]
      }
    }
    Object.keys(proto).forEach(function(key) {
      receiver.prototype[key] = proto[key]
    })
  }
是不是考虑 try-catch 一下
try{
       Object.keys(proto).forEach(function(key) {
      receiver.prototype[key] = proto[key]
    })
}catch(e){
     for (var key in proto) {
      if (proto.hasOwnProperty(key)) {
        receiver.prototype[key] = proto[key]
      }
    }
}

**Comment by lepture** [comment]
plz use es5-shim
