### ISSUE TITLE
先trigger，然后on的时候可以改成触发事件吗

### ISSUE THREAD

**Issue by 303182519** [aralejs/events#23]
存在一种情况，模块A触发了trigger事件；但是模块B是在A触发trigger的时候才进行on的绑定，所以导致模块B丢失了事件

**Comment by sehuo** [comment]
符合on、trigger预期  修改你on的顺序

**Comment by 303182519** [comment]
为什么不改成，trigger的时候假如没有的话先存下来，后面on的时候绑定的都能触发

**Comment by sehuo** [comment]
on成了不可预期，参考原生的事件流程
