### ISSUE TITLE
关于回调函数截取效率的问题

### ISSUE THREAD

**Issue by gaoli** [aralejs/events#3]
events.js 中使用循环截取传入的回调函数：

```
// Fill up `rest` with the callback arguments.  Since we're only copying
// the tail of `arguments`, a loop is much faster than Array#slice.
for (i = 1, len = arguments.length; i < len; i++) {
  rest[i - 1] = arguments[i]
}
```

使用 <code>Array.prototype.slice</code> 会使代码更精简，为什么说循环的效率会更高？

**Comment by lifesinger** [comment]
使用 Array.prototype.slice 后，速度会锐减，可以用 jsPerf 测一下，以前测过一次，找不到了。
这个 Backbone 里也测过，是可靠的性能优化。

On Thu, Nov 22, 2012 at 3:11 PM, GaoLi notifications@github.com wrote:

> events.js 中使用循环截取传入的回调函数：
> 
> // Fill up `rest` with the callback arguments.  Since we're only copying
> // the tail of `arguments`, a loop is much faster than Array#slice.
> for (i = 1, len = arguments.length; i < len; i++) {
>   rest[i - 1] = arguments[i]
> }
> 
> 使用 Array.prototype.slice 会使代码更精简，为什么说循环的效率会更高？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aralejs/events/issues/3.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by gaoli** [comment]
感谢玉伯，使用 jsPerf 测试了下性能，的确是循环的效率会高出很多！

附上测试的链接，希望对有同样疑问的人有所帮助~

http://jsperf.com/array-slice-vs-loop
