### ISSUE TITLE
是否有必要添加这样一种事件类别

### ISSUE THREAD

**Issue by concisetony** [aralejs/events#4]
类似jQuery对domready的事件处理形式。当这个事件被触发后，再绑定该事件，处理函数会直接被触发。

比如新建一个类的实例，实现需要异步加载资源（有cache），之后才能用，这时候会有一个ready事件。
但是，同一个页面周期，再次new一个实例，这时候，因为cache，资源不在需要异步加载，在新建的代码片段中，就会直接trigger('ready')。那么在新建这个实例的代码后，再on('ready')，就不会执行了。

虽然有各种办法能解决这问题，但是觉得这算个有必要的功能。

**Comment by lifesinger** [comment]
实现 promise ？

**Comment by concisetony** [comment]
嗯！

**Comment by concisetony** [comment]
接口就是 .trigger(evt, isLast);   当isLast传入true时，这个事件就是一次trigger，之后再on，就直接触发事件处理函数。

**Comment by popomore** [comment]
这个会增加 events 的复杂度，暂时没有什么场景，先不做了，如果确实有用处再支持。

**Comment by lifesinger** [comment]
需要时，可以自己引入有 promise 功能的组件来实现就好，比如 jquery 组件
